### PR TITLE
fix: Terminate with non-zero exit code on failure

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue: #

## Checklist

Please check if your PR fulfills the following requirements:

- [ ] Documentation has been added/updated
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [ ] Contains **NO** breaking changes
- [ ] Updated the Changelog
- [ ] Associated with an issue

### CODE REVIEW

**Review by Soap-141 — APPROVED** [review]
Why is this required?

**Comment by Youssef1313** [comment]
@Soap-141 There was a canary crashing by an exception (because sln file had a project that no longer exists), so the exception was printed, but the CI run was green because the tool exited with zero. So it was a silent failure.

**Review by jeanplevesque — APPROVED** [review]

**Comment by nickrandolph** [comment]
@jeanplevesque are you able to go ahead and merge this PR?

**Comment by Soap-141** [comment]
> @jeanplevesque are you able to go ahead and merge this PR?

I can do it.

**Pull request merged**
